notifications:
  email:
    on_failure: always
    on_success: change
language: python
addons:
    apt:
        packages:
            - texlive-latex-recommended
            - texlive-latex-extra
            - texlive-fonts-recommended
            - texlive-fonts-extra
            - texlive-humanities
python:
  - "3.5"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libgsl0-dev libatlas-base-dev
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda2/bin:$PATH
  - conda update --yes conda
install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib cython astropy pytest pep8
  - source activate test-environment
  - pip install -r requirements.txt
  - python setup.py build_ext --inplace
  - python setup.py install
script:
  - coverage run --source starlight -m py.test
  - pep8 starlight/*py
  - pep8 tests/*py
  - cd paper
  - make
after_success:
  coveralls
  if [ -n "$GITHUB_API_KEY" ]; then # copyright: Dan Foreman-Mackey's repos
    cd $TRAVIS_BUILD_DIR
    git checkout --orphan $TRAVIS_BRANCH-pdf
    git rm -rf .
    git add -f shrinkingparallaxes.pdf
    git -c user.name='travis' -c user.email='travis' commit -m "current pdf"
    git push -q -f https://$GITHUB_USER:$GITHUB_API_KEY@github.com/$TRAVIS_REPO_SLUG $TRAVIS_BRANCH-pdf
  fi
